model: 'mlp'
hidden_size: 1000
weight_decay: 0.0001
learning_rate: 0.001
batch_size: 50
num_epochs: 300
fmritype: 'betas_impulse'
avg_train_reps: False
target: 'blip'
roi: ['BMDgeneral']
subject: ['sub01']
  


